/**
 * updater.mjs
 *
 * Merges per-platform updater JSON manifests (generated by tauri-action)
 * into a single latest.json and publishes it to the "updater" GitHub Release tag.
 *
 * The Tauri updater plugin reads from:
 *   https://github.com/<owner>/<repo>/releases/download/updater/latest.json
 *
 * Uses only Node.js built-in modules — no external dependencies required.
 */

import https from "node:https";

// ── Config (from GitHub Actions environment) ──────────────
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPOSITORY = process.env.GITHUB_REPOSITORY;
const GITHUB_REF = process.env.GITHUB_REF;

if (!GITHUB_TOKEN) {
  console.error("❌ GITHUB_TOKEN is not set");
  process.exit(1);
}
if (!GITHUB_REPOSITORY || !GITHUB_REF) {
  console.error("❌ GITHUB_REPOSITORY / GITHUB_REF not set");
  process.exit(1);
}

const [owner, repo] = GITHUB_REPOSITORY.split("/");
const versionTag = GITHUB_REF.replace("refs/tags/", "");

// ── API helpers ────────────────────────────────────────
const API_BASE = "api.github.com";
const UPLOADS_BASE = "uploads.github.com";
const AUTH = `Bearer ${GITHUB_TOKEN}`;

function apiReq(opts) {
  return new Promise((resolve, reject) => {
    const req = https.request(
      {
        hostname: opts.uploads ? UPLOADS_BASE : API_BASE,
        method: opts.method || "GET",
        path: opts.path,
        headers: {
          Authorization: AUTH,
          Accept: "application/vnd.github+json",
          "User-Agent": "Shui-Updater/1.0",
          "X-GitHub-Api-Version": "2022-11-28",
          ...opts.headers,
        },
      },
      (res) => {
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => {
          const body = Buffer.concat(chunks).toString();
          try {
            const data = JSON.parse(body);
            resolve({ status: res.statusCode, headers: res.headers, data });
          } catch {
            resolve({ status: res.statusCode, headers: res.headers, data: body });
          }
        });
      },
    );
    req.on("error", reject);
    if (opts.body) req.write(opts.body);
    req.end();
  });
}

async function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { "User-Agent": "Shui-Updater/1.0" } }, (res) => {
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => {
        try {
          resolve(JSON.parse(Buffer.concat(chunks).toString()));
        } catch (e) {
          reject(e);
        }
      });
    }).on("error", reject);
  });
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// ── Main ────────────────────────────────────────────────
async function run() {
  console.log(`📦 Fetching release for tag: ${versionTag}`);

  // 1. Get the version release
  const getRelease = await apiReq({
    path: `/repos/${owner}/${repo}/releases/tags/${encodeURIComponent(versionTag)}`,
  });
  if (getRelease.status !== 200) {
    console.error(`❌ Failed to fetch release: ${getRelease.status}`);
    console.error(getRelease.data);
    process.exit(1);
  }
  const release = getRelease.data;
  console.log(`✅ Found release: ${release.name} (id: ${release.id})`);

  // 2. List all assets
  const listAssets = await apiReq({
    path: `/repos/${owner}/${repo}/releases/${release.id}/assets?per_page=100`,
  });
  const assets = Array.isArray(listAssets.data) ? listAssets.data : [];
  console.log(`📎 ${assets.length} total assets`);

  // 3. Find JSON manifest files (tauri-action names them: <platform>.json or latest-<platform>.json)
  const jsonAssets = assets.filter(
    (a) => a.name.endsWith(".json") && a.name !== "latest.json",
  );

  if (jsonAssets.length === 0) {
    console.log("⚠️  No updater JSON manifests found — skipping latest.json publish");
    return;
  }

  console.log(`📋 Found ${jsonAssets.length} updater manifests:`);
  jsonAssets.forEach((a) => console.log(`   - ${a.name}`));

  // 4. Download and merge all platform manifests
  const platforms = {};

  for (const asset of jsonAssets) {
    console.log(`⬇  Downloading ${asset.name}...`);
    try {
      const manifest = await fetchJson(asset.browser_download_url);
      // Merge platform entries
      if (manifest.platforms) {
        Object.assign(platforms, manifest.platforms);
      }
    } catch (err) {
      console.warn(`⚠️  Failed to download ${asset.name}: ${err.message}`);
    }
  }

  if (Object.keys(platforms).length === 0) {
    console.error("❌ No platform entries found in manifests");
    process.exit(1);
  }

  // 5. Build the merged latest.json
  const version = versionTag.replace(/^v/, "");
  const latestJson = {
    version,
    pub_date: new Date().toISOString(),
    notes: release.body || `Release ${versionTag}`,
    platforms,
  };

  const jsonContent = JSON.stringify(latestJson, null, 2);
  console.log(`\n📄 Generated latest.json (${jsonContent.length} bytes):`);
  console.log(jsonContent);

  // 6. Update the "updater" tag and release
  const updaterTag = "updater";

  // 6a. Get the commit SHA for the version tag
  const getVersionRef = await apiReq({
    path: `/repos/${owner}/${repo}/git/ref/tags/${encodeURIComponent(versionTag)}`,
  });
  if (getVersionRef.status !== 200) {
    console.error(`❌ Failed to get tag ref: ${getVersionRef.status}`);
    process.exit(1);
  }
  const targetSha = getVersionRef.data.object.sha;
  console.log(`🎯 Target commit: ${targetSha}`);

  // 6b. Delete existing updater release (if any)
  try {
    const existingRelease = await apiReq({
      path: `/repos/${owner}/${repo}/releases/tags/${updaterTag}`,
    });
    if (existingRelease.status === 200) {
      const exId = existingRelease.data.id;
      console.log(`🗑  Deleting existing updater release (id: ${exId})`);
      await apiReq({
        method: "DELETE",
        path: `/repos/${owner}/${repo}/releases/${exId}`,
      });
      await sleep(2000);
    }
  } catch (_) {
    console.log("ℹ️  No existing updater release to delete");
  }

  // 6c. Force-update the updater tag to point to the current release commit
  try {
    // Try deleting existing updater tag ref
    await apiReq({
      method: "DELETE",
      path: `/repos/${owner}/${repo}/git/ref/tags/${updaterTag}`,
    });
    console.log("🗑  Deleted existing updater tag ref");
    await sleep(1000);
  } catch (_) {
    console.log("ℹ️  No existing updater tag to delete (or delete failed)");
  }

  // Try PATCH first (update existing tag), fallback to POST (create new)
  let tagResp = await apiReq({
    method: "PATCH",
    path: `/repos/${owner}/${repo}/git/ref/tags/${updaterTag}`,
    body: JSON.stringify({ sha: targetSha, force: true }),
  });

  if (tagResp.status !== 200) {
    // PATCH failed — try POST (create new)
    tagResp = await apiReq({
      method: "POST",
      path: `/repos/${owner}/${repo}/git/refs`,
      body: JSON.stringify({
        ref: `refs/tags/${updaterTag}`,
        sha: targetSha,
      }),
    });
    if (tagResp.status !== 201) {
      console.error(`❌ Failed to create updater tag: ${tagResp.status}`);
      console.error(tagResp.data);
      process.exit(1);
    }
  }
  console.log("🏷  Updater tag set");
  await sleep(1000);

  // 6d. Create a new updater release
  const createReleaseResp = await apiReq({
    method: "POST",
    path: `/repos/${owner}/${repo}/releases`,
    body: JSON.stringify({
      tag_name: updaterTag,
      name: "Updater Manifest",
      body: `Auto-generated updater manifest for ${versionTag}`,
      draft: false,
      prerelease: false,
    }),
  });

  if (createReleaseResp.status !== 201) {
    console.error(`❌ Failed to create updater release: ${createReleaseResp.status}`);
    console.error(createReleaseResp.data);
    process.exit(1);
  }

  const updaterRelease = createReleaseResp.data;
  console.log(`📦 Created updater release (id: ${updaterRelease.id})`);

  // 6e. Upload latest.json as raw body (simpler than multipart)
  const uploadResp = await apiReq({
    method: "POST",
    path: `/repos/${owner}/${repo}/releases/${updaterRelease.id}/assets?name=${encodeURIComponent("latest.json")}`,
    uploads: true,
    headers: {
      "Content-Type": "application/json",
      "Content-Length": Buffer.byteLength(jsonContent),
    },
    body: jsonContent,
  });

  if (uploadResp.status !== 201) {
    console.error(`❌ Failed to upload latest.json: ${uploadResp.status}`);
    console.error(uploadResp.data);
    process.exit(1);
  }

  console.log("✅ latest.json published successfully!");
  console.log(`🔗 ${updaterRelease.html_url}/download/latest.json`);
}

run().catch((err) => {
  console.error("❌", err.message || err);
  process.exit(1);
});
